### ISSUE TITLE
Missing files and small omission in index.php

### ISSUE THREAD

**Issue by GlassGruber** [manticorp/CSVDump#10]
Hey there! 
I'm very interested in your project, tried it out but had couple troubles to make it run.

First you have a small omission in `index.php` at [line :218](https://github.com/manticorp/CSVDump/blob/master/index.php#L218) with a missing `php` after the opening tags, this caused me quite some headache to understand why on earth on my local xampp windows machine I got a parse error with unexpected `endif;`, while on a online webserver it was running: by default the xampp ini.php option `short_open_tag` is set on _Off_ so it was wrongly parsed.

The other one is a warning for missing files:

```
Warning:  include_once(D:\xampp\htdocs\local\scripts\CSVDump\CSVRunner/ajaxProcessUpdater/Manticorp/ProgressUpdater.php): failed to open stream: No such file or directory in D:\xampp\htdocs\local\scripts\CSVDump\CSVRunner\App.php on line 5

Warning:  include_once(): Failed opening 'D:\xampp\htdocs\local\scripts\CSVDump\CSVRunner/ajaxProcessUpdater/Manticorp/ProgressUpdater.php' for inclusion (include_path='.;D:\xampp\php\PEAR') in D:\xampp\htdocs\local\scripts\CSVDump\CSVRunner\App.php on line 5

Fatal error:  Class 'Manticorp\ProgressUpdater' not found in D:\xampp\htdocs\local\scripts\CSVDump\CSVRunner\App.php on line 7
```

Your script looks very promising, the processor feature is really interesting, thank you for your effort and sharing this work! :)

**Comment by manticorp** [comment]
Hello there,

Thanks a lot for taking an interest! I'll update the index.php momentarily, unless you want to do a Pull Request?

Regarding the missing files - this project uses a sub module, if I recall correctly, so when you download it, you should use:

    git clone https://theprojecturl.git --recursive

Otherwise it won't download the submodule :)

See: https://git-scm.com/book/en/v2/Git-Tools-Submodules

**Comment by manticorp** [comment]
Hello there,

Thanks a lot for taking an interest! I'll update the index.php momentarily, unless you want to do a Pull Request?

Regarding the missing files - this project uses a sub module, if I recall correctly, so when you download it, you should use  `git clone https://theprojecturl.git --recursive` otherwise it won't download the submodule :)

See: https://git-scm.com/book/en/v2/Git-Tools-Submodules

In reality, I should probably do this dependency management with composer - using submodules is confusing as hell.

**Comment by manticorp** [comment]
I have updated `index.php` and added instructions in the `README` to point out it should be cloned `--recursive`ly.

**Comment by GlassGruber** [comment]
Nice! Unfortunately tho the `--recursive` simply put returns blank on the terminal, as well `$ git init`, `$ git update` and `$ git status`: the ajaxProcessUpdater folder isn't even created.

I had to manually do an add for the submodule via 
`$ git submodule add https://github.com/manticorp/ajaxProcessUpdater.git CSVRunner/ajaxProcessUpdater` and then the submodule got fetched correclty.

Unfortunately I'm quite a novice with git, can't tell why the recursive is not working on the first clone, but it's a minor nuissance.

**Comment by manticorp** [comment]
Aha yeah, actually I had to make a small change to the repo for it to work - the committed version should work with --recursive now :+1:
