### ISSUE TITLE
Error on dump with provided CSV tests

### ISSUE THREAD

**Issue by GlassGruber** [manticorp/CSVDump#11]
Hey there,
tried out to dump your provided CSV files but all of them return errors.

Trying to dump the `longTest.csv` this is the following error:

```
Oh no! Something went wrong, please try again.|

Fatal error:  Call to a member function changeColTypes() on boolean in D:\xampp\htdocs\local\scripts\CSVDump\CSVRunner\CSVRunner.php on line 145
```

The JS console then gets polluted with constant logs for `progress!` and a XHR turning in a 404 (I can see that the ending digit of that progress.json file requested is variable with every attempt to dump the CSV

```
GET XHR http://localhost/local/scripts/CSVDump/var/progress-50916.json
```

This is the URL given with your `console.log` call

```
CSVRunner/App.php?fn=D%3A%5Cxampp%5Chtdocs%5Clocal%5Cscripts%5CCSVDump%5Cinput%5ClongTest.csv&replace=false&progressFn=var/progress-51129.json&chunks=100&jp=false&db=&table=&hh=true&processor=&delimiter=&escapechar=&quotechar=&columnTypes={"Some Small Numbers":"auto","Some Big Numbers":"auto","Some Huge Numbers":"auto","Some Floats":"auto","Some Text":"auto","Some Dates":"auto","Some Long Text":"auto"}
```

I can tell that I have no problem with the DB config settings since the database is correctly acessed and the table is created with the columns, but is not populated with data. 

Though only the `longTest.csv` is able to create a table, the other 2 file attempts with dump give both the same following error:

```
Code     : 8               
File     : D:\xampp\htdocs\local\scripts\CSVDump\CSVRunner\CSVRunner.php
Line     : 389
Message  : Undefined offset: 1
```

With this error the console this time keeps returning only the `progress!` log, but no XHR request.

Debugging is not my forte I'm sorry, this is as much info I was able to cater. I've tested not only in my Win 7 machine with XAMPP but also on a online server with linux apache, and same behavior.

If I can do something else to help track this thing down let me know!

**Comment by manticorp** [comment]
Thanks a lot for all the information!

It would seem the primitive autoloader isn't finding the core DB processor file, see CSVRunner.php line 715 for the function that finds it.

Could you try replacing the line 720:

```
    }
    $fn = __DIR__ . DIRECTORY_SEPARATOR . str_replace('_',DIRECTORY_SEPARATOR,$className).'.php';
    if(!file_exists($fn)){
```

with:

```
    }
    $fn = APPLICATION_PATH . DIRECTORY_SEPARATOR . 'CSVRunner' . DIRECTORY_SEPARATOR . str_replace('_',DIRECTORY_SEPARATOR,$className).'.php';
    if(!file_exists($fn)){
```

and/or if you want more information, re-clone the repo - I've added some more debugging things that should point out if it's not finding it correctly. No idea why that shouldn't be working....

**Comment by manticorp** [comment]
Aha, I think I've solved it - for whatever reason the gitignore I was using wasn't working properly - all the right files should be in there now and _hopefully_ it should work fine :+1: 

Thanks for all your help and debugging!

Try redoing:

```
git clone https://github.com/manticorp/CSVDump.git --recursive
```

and it should work fine now (hopefully!)

**Comment by GlassGruber** [comment]
Glad I could help! :)
Now the `longTest.csv` file is dumping correctly and storing records in the table! 

Unfortunately, the other 2 files are yet giving out an error on dump (the same reported above I think)

```
Code     : 8               
File     : D:\xampp\htdocs\local\scripts\CSVDump\CSVRunner\CSVRunner.php
Line     : 394
Message  : Undefined offset: 1
```

I'll try with some CSV files I'm working with to see if it's a particular issue with the test ones provided.

**Comment by manticorp** [comment]
Hmmm...interesting, I could replicate the first bug, but this one I cannot...

Bear with me now, cos I'm thinking out loud.

The lines in question are:

```
        $colTypes = array_fill(0,count($cols),null);
        for($i = 0; $i < $n; $i++){
            foreach ($cols as $j => $col) {
                $colTypes[$j] = $this->guessType($firstNCols[$i][$j], $colTypes[$j]);
            }
        }
```

Basically, this is the part that tries to guess the datatypes of each column - it'll loop through the first `$n` rows of data and for each column[`$j`] it will take a best guess at the column type, taking into account the last guesses.

So, we're either getting an error on the `$colTypes` array, which is unlikely, because it's filled just above by the count of cols, so it's probably to do with the $firstNCols array, which is an array of the first `$n` rows of the datasource, with sub-arrays of columns

And we know it's either going to be the `$i` or `$j` variable causing the issue, so it's either not reading enough lines, or it's not reading enough columns...

And I'd say it's unlikely to not be reading the right amount of lines...so, it might just be the amount of columns...

Now, I'm gonna take a stab in the dark here, and say that you're maybe German? This _may_ be a localisation issue in that case...to do with default CSV delimiters.

The way the software guesses CSV delimiters is, if it exists, via the [`SplFileObject::getCsvControl()`](http://php.net/manual/en/splfileobject.getcsvcontrol.php) method, which I _think_ is localised, and I know delimiters _differ_ across countries.

One thing you can try is _explicitly_ setting the delimiters to `,` , `"` and `\` for the delimiter, quotechar and escapechar respectively under the 'advanced options' button.

If that _doesn't_ work...then maybe there's something else...

One difference between the test files is that `longTest.csv` has no newlines in the data itself, whereas the other two do.

Can you make a test file to see if this is causing the issues? If that's the case, it may be the quote character again.

One thing you can do is try changing the lines above in CSVRunner.php to:

```
        $colTypes = array_fill(0,count($cols),null);
        for($i = 0; $i < $n; $i++){
            foreach ($cols as $j => $col) {
                if(!isset($firstNCols[$i])){
                    trigger_error('Why don\'t we have row ' . $i . '??');
                }
                if(!isset($firstNCols[$i][$j])){
                    if(count($firstNCols[$i]) !== count($cols)){
                        trigger_error('Column count is inconsistent throughout the file. If you\'re sure you have the right amount of columns, please check the delimiter options.');
                    }
                    trigger_error('Why don\'t we have column ' . $j . '??');
                }
                $colTypes[$j] = $this->guessType(
                    $firstNCols[$i][$j],
                    $colTypes[$j]
                );
            }
        }
```

and this might help with debugging a bit...

I've updated the repo to include these lines, so you can just pull down the changes :+1: 

Thanks again for the help!

**Comment by GlassGruber** [comment]
Hey there!
No I'm not German (ye my nick and grav are misleading! :P ) and my system is setup with English language (tho the format is set on Italian). I've tested both setting my self the delimiters and leaving them as auto, result is the same.

I'm slowly learning to debug a bit (set up Xdebug with sublime text, is not ideal but kinda working [btw can you suggest me a standalone debugger of some?]) and I can tell that something fishy is happening with the file reading.

Dumping the `test.csv` file this is what is stored in the `$firstNCols` array:

```
$firstNCols = array[10]
  $firstNCols[0] = array[7]
    $firstNCols[0][0] = (string) 1
    $firstNCols[0][1] = (string) 1.1
    $firstNCols[0][2] = (string) 1.111
    $firstNCols[0][3] = (string) Hello
    $firstNCols[0][4] = (string) oyRAOiEio30=
    $firstNCols[0][5] = (string) Multiline Field With Lots  Of   Lines
    $firstNCols[0][6] = (string) NULL
  $firstNCols[1] = array[7]
    $firstNCols[1][0] = (string) 1
    $firstNCols[1][1] = (string) 1
    $firstNCols[1][2] = (string) 1
    $firstNCols[1][3] = (string) 1
    $firstNCols[1][4] = (string) 1
    $firstNCols[1][5] = (string) 1
    $firstNCols[1][6] = (string) 1
  $firstNCols[2] = array[7]
    $firstNCols[2][0] = (string) ABC
    $firstNCols[2][1] = (string) DEF
    $firstNCols[2][2] = (string) GHI
    $firstNCols[2][3] = (string) JKL
    $firstNCols[2][4] = (string) MNO
    $firstNCols[2][5] = (string) PQR
    $firstNCols[2][6] = (string) STU
  $firstNCols[3] = array[1]
    $firstNCols[3][0] = <null>
  $firstNCols[4] = <null>
  $firstNCols[5] = <null>
  $firstNCols[6] = <null>
  $firstNCols[7] = <null>
  $firstNCols[8] = <null>
  $firstNCols[9] = <null>
```

As you can see in `$firstNCols[0][4]` the stored value is `oyRAOiEio30=`, while the in the CSV file there should be something like `?$@:!""?}`, below the CSV table (github don't like it attached :| )

```
+---------------+---------------+-------+-------+----------+-------------------------------+------+
| Column Name 1 | Column Name 2 | Foo   | Bar   | Baz      | Spam                          | Eggs |
+---------------+---------------+-------+-------+----------+-------------------------------+------+
| 1             | 1.1           | 1.111 | Hello |?$@:!""?} | MultilineFieldWithLotsOfLines | NULL |
+---------------+---------------+-------+-------+----------+-------------------------------+------+
| 1             | 1             | 1     | 1     | 1        | 1                             | 1    |
+---------------+---------------+-------+-------+----------+-------------------------------+------+
| ABC           | DEF           | GHI   | JKL   | MNO      | PQR                           | STU  |
+---------------+---------------+-------+-------+----------+-------------------------------+------+
```

Opening the CSV file in a text editor I can see is composed of 12lines (counting the returns).

Also as you can see `$firstNCols` has 10 stored arrays, though the last 6 arrays are `<null>` so when the function reach `if(!isset($firstNCols[$i][$j]))` it will fail inevitably am I correct?

Atm this is what is reported as error at line [399](https://github.com/manticorp/CSVDump/blob/master/CSVRunner/CSVRunner.php#L399)

```
Code     : 1024            
File     : D:\xampp\htdocs\local\scripts\CSVDump\CSVRunner\CSVRunner.php
Line     :  399
Message  : Column count is inconsistent throughout the file. If you're sure you have the right amount of columns, please check the delimiter options.
```

This is as much I was able to "debug" on my own, hope it can turn useful!

**Comment by manticorp** [comment]
That helped a lot :+1: 

Do a pull or update, it should be working now!

The problem was, when I was testing, I was just dumping to the database `test` and table `test`, which already existed, so that method wasn't even firing for me.

Latest commit should fix the issue :) it basically makes sure we count the number of _rows_ accurately in the case there's not that many lines in the file.

Regarding debugging - XDebug is excellent, but can be _very_ slow, especially with certain programs (e.g. PHPMyAdmin).

I use a [chrome extension to easily turn debugging and profiling on and off](https://chrome.google.com/webstore/detail/xdebug-helper/eadndfjplgieldjbigjakmdgkmoaaaoc), but to be honest, I turn it off in php.ini 90% of the time. I don't integrate with Sublime Text because of how I have things set up, I just look at cachegrind files manually using kcachegrind and insert debug points manually.

Other than that, [Zend Server](http://www.zend.com/en/products/zend_server) has some excellent debugging, profiling and helper tools (Z-Ray is nice), but it's no longer got a free edition for everyone - though you can apply if you are a student or you are working on Open Source projects.

I haven't found anything better yet! Although you can maybe check my (probably hugely bug ridden now) timing and benchmarking library, if that is of interest to you ;)

https://github.com/manticorp/PHP-Timer-Benchmarker

Thanks a lot for your help!

**Comment by GlassGruber** [comment]
I'm very glad I gave you useful insight to track down this last issue!
Now everything is working with your included CVS files, I'll soon play around with some CSV I have and make some tests, and thank you for your useful tips! :)

We can finally close this :+1: :hand:
